#!/root/.rbenv/shims/ruby

class MuninIptablesStat
    def initialize argv
        @argv = argv
        @tags = ENV['TAGS']
            .to_s
            .strip
            .split(/\s+/)
    end
        
    def cli 
        case @argv[0]
        when 'config'
            config
        when 'install'
            install
        else
            run
        end
    end

    private

    def config
        puts <<-CONFIG
graph_category #{ENV['GRAPH_TITLE']}
graph_title Packets/s
graph_vlabel packets/s
graph_args --base 1000 -l 0

CONFIG

        @tags.each do |tag|
            t = tag.downcase
            puts "#{t}.label #{t}"
            puts "#{t}.type DERIVE"
            puts "#{t}.min 0"
        end

        exit 0
    end

    def run
        get_stats.each_pair do |k, v|
            puts "#{k}.value #{ v || 0 }"
        end

        exit 0
    end

    # Util

    def get_stats
        stat = {}

        # Sample line:
        #     641    45979 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* DNS_ACCEPT */
        reg = /
            ^\s*
            (\d+)
            .*
            \/\*\s(#{ @tags.join '|' })\s\*\/
        /x

        `iptables -v -x -n -L`.each_line do |line|
            if line =~ reg
                stat[$2.downcase] = $1.to_i
            end
        end

        stat
    end

    # /usr/local/sbin/iptables_stat_ install dns 'Firewall DNS' 'DNS_ALL DNS_BR DNS_AWS DNS_OVERRATE DNS_ACCEPT'

    def install
        plugin_title = @argv[2]
        graph_title = @argv[3]
        iptables_tags = @argv[4]

        target = File.expand_path(__FILE__)
        fname = "#{File.basename target}_#{plugin_title}"

        # plugin symlink
        system "ln -s #{target} /etc/munin/plugins/#{fname}"

        # munin_node_conf
        munin_node_conf = "\n[#{fname}]\nuser root\n"
        munin_node_conf += "env.GRAPH_TITLE #{graph_title}\n\n"
        munin_node_conf += "env.TAGS #{iptables_tags}\n\n"

        File.open('/etc/munin/plugin-conf.d/munin-node', 'a').write munin_node_conf
    end

    def error msg
        STDERR.puts msg
        exit 1
    end
end

MuninIptablesStat.new(ARGV).cli
